name: Lint-php

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.1", "8.2", "8.3", "8.4" ]
    name: php-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          cd ${{ github.workspace }}
          find . -name \\*.php -not -path './lib/composer/*' -not -path './lib/Vendor/*' -not -path './build/stubs/*' -print0 | xargs -0 -n1 php -l

  phpcs:
    runs-on: ubuntu-latest
    name: phpcs
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpcs
      - name: Run phpcs
        run: |
          phpcs --standard=./ruleset.xml --extensions=php,module,inc,install --ignore=node_modules,bower_components,vendor,lib/Vendor,3rdparty,Migration --warning-severity=0 ./
