name: Lint-php

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.0", "8.1", "8.2" ]
    name: php-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          cd ${{ github.workspace }}
          find . -name \\*.php -not -path './lib/composer/*' -not -path './build/stubs/*' -print0 | xargs -0 -n1 php -l